##
## Jamn JPSApp Config Properties
##

#Profile
jps.profile=app

#HTTP Server port
http.server.port=9090

#System Web files root folder
#intended for the system web app
#no drive letter, start with '/' = absolute path, else relative to jar or to start folder
#DO NOT change unless absolutely necessary
jps.web.root=http

#User Web files local folder
#intended for web app customization
#no drive letter, start with '/' = absolute path, else relative to start folder
#e.g. /my-local-path/user-http, user-http
jps.user.web.local.root=user-http

#WebApp main Page
jps.webapp.main.page=/workbench.html

#Web content cache mode
jps.web.cache.load.onstartup=true

#Web content caching enabled
jps.web.cache.caching.enabled=true

#Extensions root folder name
jps.extension.root=extensions

#Extensions bin folder name
jps.extension.bin=bin

#Extensions data folder name
jps.extension.data=data

#Command task worker
jps.command.task.worker=10

#Workspace root folder
jps.workspace.root=workspace

#Data root folder
jps.data.root=data

#JavaScriptProvider script root folder
jps.script.root=scripts

#JavaScript auto-load script
jps.js.auto.load.script=js-auto-load.js

#JavaScript enabled
jps.javascript.enabled=true

#JavaScript debug enabled
jps.javascript.debug.enabled=false

#WebSocket url root
jps.websocket.url.root=/wsoapi

#WebSocket max upstream size
jps.websocket.max.upstream.size=65000

#WebSocket Task worker threads
jps.websocket.task.worker=10

#WebService url root
jps.webservice.url.root=/webapi

#Standard encoding
jps.standard.encoding=UTF-8

#Windows shell encoding
jps.win.shell.encoding=Cp850

#Unix shell encoding
jps.unix.shell.encoding=ISO8859_1

#JVM debug option
jvm.debug.option=-agentlib:jdwp=transport=dt_socket,address=localhost:9009,server=y,suspend=y

##
##  Server Config Properties
##

#Max concurrent HTTP/WebSocket connections
http.max.connections=200

#Max HTTP header size in bytes
http.max.header.size=16384

#Max HTTP request body size in bytes
http.max.content.length=5242880

#Socket timeout in millis
http.client.socket.timeout=500

#Use Connection:keep-alive header
http.connection.keep.alive=true

#Http encoding
http.encoding=UTF-8

#A Global Cross origin flag
#if=true ALL cors requests are allowed
http.allow.all.cors.enabled=false

#HTTP CORS
http.cors.allow.origin=localhost
http.cors.allow.methods=GET, POST, OPTIONS
http.cors.allow.headers=Origin, Content-Type, Authorization
