##
## Jamn JPSApp Config Properties
##

#Profile
jps.profile=app

#HTTP Server port
http.server.port=9090

#Web files root folder
#(no drive letter, start with '/' = absolute path)
jps.web.root=http

#WebApp main Page
jps.webapp.main.page=/workbench.html

#Web content cache mode
jps.web.cache.load.onstartup=false

#Extensions enabled
jps.extensions.enabled=true

#Extensions root folder name
jps.extension.root=extensions

#Extensions bin folder name
jps.extension.bin=bin

#Extensions data folder name
jps.extension.data=data

#Extensions auto load file name
jps.extensions.autoload.file=extensions-auto-load.json

#Workspace root folder
jps.workspace.root=workspace

#Data root folder
jps.data.root=data

#JavaScriptProvider script root folder
jps.script.root=scripts

#JavaScript auto-load script
jps.js.auto.load.script=js-auto-load.js

#JavaScript enabled
jps.javascript.enabled=true

#JavaScript debug enabled
jps.javascript.debug.enabled=false

#WebSocket url root
jps.websocket.url.root=/wsoapi

#WebSocket max upstream size
jps.websocket.max.upstream.size=65000

#WebSocket Task worker threads
jps.websocket.task.worker=5

#WebService url root
jps.webservice.url.root=/webapi

#Server enabled
jps.server.enabled=true

#WebService enabled
jps.webservice.enabled=true

#WebSocket enabled
jps.websocket.enabled=true

#Server autostart
jps.server.autostart=true

#Standard encoding
jps.standard.encoding=UTF-8

#Windows shell encoding
jps.win.shell.encoding=Cp850

#Unix shell encoding
jps.unix.shell.encoding=ISO8859_1

#JVM debug option
jvm.debug.option=-agentlib:jdwp=transport=dt_socket,address=localhost:9009,server=y,suspend=y

##
##  Server Config Properties
##

#Max HTTP worker threads
http.worker=5

#Socket timeout in millis
http.client.socket.timeout=500

#Use Connection:keep-alive header
http.connection.keep.alive=true

#Http encoding
http.encoding=UTF-8

#A Global Cross origin flag
#if=true ALL cors requests are allowed
http.allow.all.cors.enabled=false

#HTTP CORS
http.cors.allow.origin=localhost
http.cors.allow.methods=GET, POST, OPTIONS
http.cors.allow.headers=Origin, Content-Type, Authorization
