# used handler
handlers=java.util.logging.ConsoleHandler, java.util.logging.FileHandler

#console
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter

#file
java.util.logging.FileHandler.formatter=java.util.logging.SimpleFormatter
java.util.logging.FileHandler.append=false
java.util.logging.FileHandler.pattern=jps.log
#The maximum size of the file, in bytes. If this is 0, there is no limit.
#The default is 1000000 (which is 1 MB). Logs larger than 1MB roll over to the next log file.
java.util.logging.FileHandler.limit=1000000
#The number of log files to use in the log file rotation.
java.util.logging.FileHandler.count=1

#handler level
java.util.logging.ConsoleHandler.level=ALL
java.util.logging.FileHandler.level=ALL

#logger level
iqb.jps.level=ALL


# Formatting
# see: https://docs.oracle.com/en/java/javase/17/docs/api/java.logging/java/util/logging/SimpleFormatter.html
#Java JDK Doc SimpleFormatter args:
# 0 format
# 1 date
# 2 source
# 3 logger
# 4 level
# 5 message
# 6 thrown

# Sample Formats
#
# prints: message \n
# java.util.logging.SimpleFormatter.format=%5$s %n
#
# prints: [date time] source \n message \n
java.util.logging.SimpleFormatter.format=%n[%1$tF %tT] %4$s %2$s %n %5$s%6$s