appname=${jps.app.name}
app.class.name=${jps.app.class}
version=${jps.app.version}
jar.libsdir=${jps.executable.libs.dir}
jar.temp.dir.prefix=${jps.executable.temp.dir.prefix}
description=${jps.app.description}
url=${project.url}
readme.url=${project.url}
build.date=${build.timestamp}
author=${author}
author.url=${authorUrl}
jps.javascript.enabled=${jps.javascript.enabled}