<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>iqb.jps.sample</groupId>
		<artifactId>jpsapp-sample-project</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>

	<groupId>iqb.jps.sample</groupId>
	<artifactId>jpssample-jsplayground</artifactId>

	<name>${project.artifactId}</name>
	<description>Sample JS Playground Extension for JPSApp.</description>
	<url>${parent.url}</url>

	<properties>
		<do.distribution>true</do.distribution>
	</properties>

	<dependencies>
		<dependency>
			<groupId>iqb.jps</groupId>
			<artifactId>${jpsapp.artefactid}</artifactId>
		</dependency>

		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<release>${java.version}</release>
				</configuration>
			</plugin>

			<plugin>
				<artifactId>maven-source-plugin</artifactId>
				<executions>
					<execution>
						<id>attach-sources</id>
						<goals>
							<goal>jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-antrun-plugin</artifactId>
				<executions>
					<execution>
						<phase>install</phase>
						<configuration>
							<target if="${do.distribution}">
								<copy file="target/${project.artifactId}-${project.version}.jar"
									tofile="${jps.extensions.bin}/${project.artifactId}-${project.version}.jar" />
							</target>
						</configuration>
						<goals>
							<goal>run</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

		</plugins>
	</build>

</project>