<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>iqb.jps</groupId>
		<artifactId>jaman-jpsapp-project-parent</artifactId>
		<version>0.0.1-SNAPSHOT</version>
		<relativePath>../pom.xml</relativePath>
	</parent>

	<groupId>iqb.jps</groupId>
	<artifactId>jpsapp-extension-parent</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>pom</packaging>

	<name>JPSApp Extension Parent</name>
	<description>A Parent POM for standalone JPSApp extension projects.</description>
	<url>https://github.com/iqbserve/JamnJPSApp</url>

	<properties>
		<jps.target.app.version>${project.version}</jps.target.app.version>
		<jps.extension.api.artifactId>jpsapp-core</jps.extension.api.artifactId>
		<jps.extensions.bin>./extensions/bin</jps.extensions.bin>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>iqb.jps</groupId>
				<artifactId>${jps.extension.api.artifactId}</artifactId>
				<version>${jps.target.app.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<configuration>
						<release>${java.version}</release>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>

</project>
